### ISSUE TITLE
Kernel debuginfo to run Systemtap and other kernel tracing/profiling tools

### ISSUE THREAD

**Issue by dannyk81** [coreos/toolbox#50]
# Feature Request #

Have been a long time CoreOS user and generally I'm very happy with the ecosystem and tools, however recently we've been working to troubleshoot network performance issues that have led us to tools like [Systemtap](https://sourceware.org/systemtap/) to better understand some behaviors that are occurring on the kernel level.

The toolbox being a fedora is a blocker here, since we need an exact match of all the related kernel debug/devel/build data that CoreOS is running but we can only install from fedora repos inside toolbox which doesn't match the running kernel.

## Desired Feature ##

We would like to be able to run low-level probing/tracing tools such as Systemtap on CoreOS, whether native or from toolbox.

I suppose, if kernel debuginfo package (and others) with the matching build config and version were available for installation in toolbox this should provide what is necessary 
for these tools to work.

**Comment by dm0-** [comment]
Assuming "CoreOS" here refers to the Container Linux distro (since this repo is now involved in Red Hat CoreOS and Fedora CoreOS), have you tried the [developer container](https://alpha.release.core-os.net/amd64-usr/current/coreos_developer_container.bin.bz2)?  You can download that for your specific OS version and run it as a systemd-nspawn image with `--share-system` to get access to the development files that built the production OS image.  Run `emerge-gitclone` pull down package definitions in the container.

Note that if you install kernel debuginfo, you'll probably have to extend the image, partition, and file system to have enough disk space.  (Maybe bind-mounting `/usr/lib/debug` and/or `/usr/lib/modules` from the host would also work.)  To install debuginfo, drop the `/usr/lib/debug` from `INSTALL_MASK` in `/var/lib/portage/coreos-overlay/profiles/coreos/targets/generic/dev/make.defaults`, then run `sudo emerge -gv coreos-{kernel,modules,sources}`.

Since systemtap isn't included in our repos, you would have to pull it from Gentoo.  I don't recall a clean way to do that in the developer container, so you can just `git clone --depth=1 https://github.com/gentoo/gentoo.git` and copy its `dev-util/systemtap` into the same location in `/var/lib/portage/portage-stable` and run `sudo emerge -gv systemtap`.

**Comment by dannyk81** [comment]
Thanks @dm0-! I'm going to give it a try.

I was referring to `CoreOS Container Linux`

**Comment by dannyk81** [comment]
@dm0- many thanks!

Using the binary packages above, I was able to get systemtap working in the fedora toolbox on CoreOS Container Linux.

High Level steps if anyone's interested:
1) Download and extract all three (`kernel,modules,sources`) packages under root (/)
2) Download and build systemtap from source (don't install the fedora package, but dependencies can be fulfilled using `dnf`)
3) Modify `UTS_VERSION` in `/usr/lib/modules/{version}-coreos/build/include/generated/compile.h` to match the output of `uname -v`

With above systemtap seems to work as expected from the toolbox container.

**Comment by phylake** [comment]
@ dannyk81 `kernel.function` don't appear to work with this setup. Do they work for you?

`stap -L 'kernel.function("netif_rx")'` (for example) shows the right line number in the Linux source but `stap -e 'probe kernel.function("*") { printf("im alive\n") }'` never prints

kprobes and traces work for me

**Comment by dannyk81** [comment]
@phylake sorry for the late reply, just got back from vacation :sweat_smile: 

interesting, I didn't use `kernel.function` for my specific troubleshooting use case, so not sure, but this "should" work.
